kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  index.html: |
   <html>
   <h1>Welcome</h1>
   </br>
   <h1>hello from Abdelkhalek</h1>
   </html 